<Project Sdk="Godot.NET.Sdk/4.7.1">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <Nullable>enable</Nullable>
    <LangVersion>14</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="script_templates\empty.cs" />
    <None Include="script_templates\empty.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Tomlyn" Version="2.10.1" />
    <PackageReference Include="TupleAsJsonArray.Redux" Version="1.1.0" />
  </ItemGroup>
</Project>
